### ISSUE TITLE
Double vote bug

### ISSUE THREAD

**Issue by lunatixxx** [L4D-Community/builtinvotes#3]
Player call a vote to change campaign, vote result is no.
Few seconds later custom vote to start match but it still show change campaign vote so veto to cancel it we hear the sound, but it still changed the map it in the end.
Was it because the last vote was not well terminated or because someone asked again the change campaign vote at the same time of the custom vote?

I had an older version tho, maybe it is patched in the last.

**Comment by A1mDev** [comment]
I'll close the issue for now, if this happens again, you can reopen it.
