### ISSUE TITLE
DisplayBuiltinVotePass bug

### ISSUE THREAD

**Issue by dewobedil** [L4D-Community/builtinvotes#5]
**DisplayBuiltinVotePass** in left 4 dead 2 doesnt work and nothing happen or error in console
i tried using your **buildinvotes_test.sp**

also i tried recompile the extension but i got **undefined symbol: _ZdlPvj** in linux when load the ext
im using gcc & g++ 5.5 and latest sourcemod 1.10

**Comment by A1mDev** [comment]
If you are using sourcemod 1.11, this extension needs to be updated. You don't need to rebuild anything, you can download the builtinvote extension [here](https://github.com/L4D-Community/builtinvotes/actions/runs/1773038347) (GitHub Actions). This [problem](https://github.com/L4D-Community/L4D2-Competitive-Framework/issues/6) has already been resolved...

**Comment by dewobedil** [comment]
Thank you for the help!! i thought the latest update is from releases
case closed and fixed using `Actions` build!
one more thing why i got *undefined symbol: _ZdlPvj* when recompile the exts using sourcemod 1.10 ?

**Comment by A1mDev** [comment]
I think your compiler is misconfigured. Try using clang and ambuild instead of gcc and makefile. Example how to change the compiler in ambuild:
```CC=clang CXX=clang python3 ../configure.py --sdks l4d2 --enable-optimize --sm-path ../../sourcemod```

**Comment by dewobedil** [comment]
wait nvm
it still happening i just tested it using *builtinvotes-sm1.10-linux-1e12289*

im using sourcemod 1.10 - build 6528 what im missing
the vote passed but the screen still there

**Comment by A1mDev** [comment]
I don't know, post the code you are using and demo

**Comment by dewobedil** [comment]
Nvm i fixed it
it was this plugin that causing the bug
https://forums.alliedmods.net/showthread.php?t=316913
